### ISSUE TITLE
initialisation issue

### ISSUE THREAD

**Issue by alex-n-braun** [alex-n-braun/carla.hal#16]
- there is a problem with self.state in tl_detector.py
- in some cases, this variable is not available during call to image_cb
- possible reason: call to image_cb *before* constructor is done
- happens on my (alex) machine when simulator is already running before roslaunch ...

**Comment by YCSU** [comment]
I got exactly the same issue. I then moved all the variable initialisation before all the subscribers and the problem is gone.

I can fix it directly without a pull request. Is that okay?

**Comment by YCSU** [comment]
I can fix it directly without a pull request. Is that okay?

**Comment by dyh1213** [comment]
Hey YCSU, did you apply the fix?

**Comment by YCSU** [comment]
Not yet. but as long as you open the simulator first, there shouldn't be any problem.

**Comment by dyh1213** [comment]
Using the current master and opening the simulator first I still get an error
AttributeError: 'TLDetector' object has no attribute 'state'
When I launch ros first no error, but car simply stands still.
