### ISSUE TITLE
Take max speed from waypoint_loader instead of using 10mph directly

### ISSUE THREAD

**Issue by alex-n-braun** [alex-n-braun/carla.hal#25]

**Comment by dyh1213** [comment]
Hey can you explain this issue? I didnt quite understand whats wrong with the current method.

**Comment by alex-n-braun** [comment]
Well, the requirement by Udacity changed. Have a look here: https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/462c933d-9f24-42d3-8bdc-a08a5fc866e4/concepts/afb9f3b2-58d7-4ec6-88f3-fc4f84d9a8a1

last sentence.

Initially they required us to limit the max speed to 10mph. They removed this requirement and replaced it with " Be sure to limit the top speed of the vehicle to the km/h velocity set by the velocity rosparam in waypoint_loader. "

They will instantly see that we dont meet this requirement if they set 'velocity=0'.

**Comment by alex-n-braun** [comment]
done
